### ISSUE TITLE
[suggestion] more insulating glasses 

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#1]
at least blue/brown, which were also common colours for antique glass insulators

I dont know how reasonable it would be to oredict them with IE's

**Comment by stfwi** [comment]
Would not have an effect on the IE insulators themselves. These don't have a tintable design, see

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/textures/blocks/connector_relay_hv.png

So, I am a bit hesitant there (also because as I am not a professional modder). There is another gameplay thing to take into account, when you see a green insulator you don't touch it ;)

**Comment by majijn** [comment]
I know! I was more asking for insulated glass blocks, because I sometimes use them for some of my astral sorcery set ups, but green doesnt go as well as brown or blue would in those set ups (because Astral sorcery's main block pallete involves whites, blacks, blues, and browns and some gold as highlights)

**Comment by stfwi** [comment]
I understand, uhhm, don't like to say that.. it's out of IE scope and a really very and occasional use, so I'll pass on this one.
