### ISSUE TITLE
LoaderExceptionModCrash - Bad Local Variable Type

### ISSUE THREAD

**Issue by madmax3004** [stfwi/engineers-decor#103]
Minecraft: 1.12.2
Engineer's Decor: 1.1.0
Immersive Engineering:  0.12-98
forge-14.23.5.2854

Crash log:
https://pastebin.com/EmgGtnPS

**Comment by madmax3004** [comment]
Had a quick look at this issue: https://github.com/stfwi/engineers-decor/issues/102

And that might be the same error? That user hasn't posted his versions / complete crash log though, so I can't compare mods and see if there's a potential mod conflict of a mod we both have.

**Comment by stfwi** [comment]
Hi, that's a strange one. The exception is thrown when accessing the Furnace TE, which is the first in the config `apply()` function. Looking in the decompiled code of the TE, `func_73660_a()` is the `update()` method, not invoked at all in that phase. And that method is also not in line 438.

No changes in the config since last release version, but I added a blockstate check in the update() methods (in case the TEs get moved by a modded piston). So that would be theoretically my anchor to start with.

I can't reproduce that meself, is is reproducible on your machine?

**Comment by madmax3004** [comment]
Still a crash:
https://pastebin.com/TaTKMMKX

**Comment by stfwi** [comment]
Ok, I won't say "perfect" now as it would definitely not fit, I gonna clear my complete gradle cache and change that state check line in the update function, and would then attach a testing file into this thread, if that is okay with you.

**Comment by stfwi** [comment]
Test jar would be this then: 
[2020-06-30-engineersdecor-1.12.2-1.1.1-b1.zip](https://github.com/stfwi/engineers-decor/files/4852395/2020-06-30-engineersdecor-1.12.2-1.1.1-b1.zip)

**Comment by erebus42** [comment]
Re-posting crash log here as well: [crash-2020-06-28_23.27.41-client.txt](https://github.com/stfwi/engineers-decor/files/4853064/crash-2020-06-28_23.27.41-client.txt)

**Comment by stfwi** [comment]
Thanks, according to that crash log the version 1.12.2-1.1.0-b2 was already affected.

**Comment by stfwi** [comment]
We have a third report about this, log: https://pastebin.com/wdQjz2tc by @StormbringerGTX ("welcome on board") ;-).

**Comment by StormbringerGTX** [comment]
Ah, wasn't sure this was related.

Interesting to note that this crash isn't consistent. I've just loaded the game about a dozen more times refining my modpack and it hasn't crashed since. Hope it helps, but that probably makes it worse?

EDIT
Never mind I forgot I quarantined the bug during test, still crashes every time for me.

**Comment by stfwi** [comment]
Ok guys, researching a bit has yielded that this could be related to a bug in java, that I managed to provoke during the last changes. I have here a test version, where the config in is re-arranged in the classes.
Could you try this mod file and give me feedback if it works then? Cheers -
[2020-07-01-engineersdecor-1.12.2-1.1.1-b1.zip](https://github.com/stfwi/engineers-decor/files/4859711/2020-07-01-engineersdecor-1.12.2-1.1.1-b1.zip)

**Comment by teagan75** [comment]
I too experienced this crash. The above update allowed me to load the game

**Comment by madmax3004** [comment]
Apologies, I haven't had time to test the fix attempts. I'll be able to give it a try this weekend.

**Comment by stfwi** [comment]
Ok @teagan75 ty for checking.

**Comment by StormbringerGTX** [comment]
Fix seems to be working for me
About 12 launches and no issues.

**Comment by teagan75** [comment]
same. Several launches and no issues

**Comment by stfwi** [comment]
Perfect that guys. I dared to push that as v1.1.1-b1 to Curse. If no further trouble is dropping in it's gonna be the maintenance release in about a week. Thanks again all for testing the test versions!

**Comment by stfwi** [comment]
Alright, engineersdecor-1.12.2-1.1.1 maintenance release is up as they were no further occurrences of the problem. Closing this then. Cheers all!
