### ISSUE TITLE
[suggestion] have panzer glass be a transparent ceramic such as aluminium oxynitride

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#11]
feel free to ignore this but personally for me it would make more sense if the glass was made of something like [aluminium oxynitride](https://en.m.wikipedia.org/wiki/Aluminium_oxynitride) instead of some diamonds, steel rods and some.plain glass. 
plus if its made out of alum.oxynitride the recipe could use existing materials from IE (namely aluminium grit and nitrate dust!

**Comment by stfwi** [comment]
Ya I'm open to recipe adaptions. The important thing is that the blocks are fairly expensive in the materials used, but comparatively quickly crafted and somehow still well to remember. (expensive because it would be OP otherwise). So it's similar to rebar concrete, but with glass because it's glass, and a diamond to indicate hardened the glass. It's also important to have limiting factors for comparatively powerful blocks. Early game this is the steel and the diamond. People have to decide if they want that glass or other things needed. Late game, steel is automated, but diamond still has to be mined - so it's easier but not unlimited. --- that's how it came to this recipe.

**Comment by stfwi** [comment]
Let's see how this works out and adapt it if needed.

**Comment by stfwi** [comment]
From the game play (yes I found some time to actually play again ;) ) the recipe seems to work out well. For mod packs I added a config option to disable all recipes and define own recipes. So I'd like to close this issue - but thanks nonetheless for contributing!
