### ISSUE TITLE
[1.16.1] cycling sign recipes not functioning.

### ISSUE THREAD

**Issue by NickPancakes** [stfwi/engineers-decor#111]
Hey there, apologies if this is all functioning fine for you and it's some conflict in our modpack, but I believe it is not.

We're playing with 1.1.1b4 on 1.16.1 on forge 32.0.77.

The recipe for Sign "Caution Hot Wire" functions just fine, but the recipe for turning it into "Caution Really Dangerous There" does not. Likewise, after /give-ing myself a sign_danger, the recipe to construct it into a "Caution Defense System Ahead" does not function.

**Comment by stfwi** [comment]
Hi, ok, gonna check that out at the weekend.

**Comment by stfwi** [comment]
Actually, could you attach a log, because I use the "conditional recipe" system, where there should be lines like "skipped recipe xyz because serializer returned null". This would be an indication that something's wrong with the conditions. However, there are no dependencies of in the sign recipes except that the blocks are not opted out. And that would have to be explicitly done in the config. So a strange thing that we can better track back when looking into a log.

**Comment by NickPancakes** [comment]
I don't see anything in the logs, but I believe the problem might actually be on Placebo's end and related to this: https://github.com/Shadows-of-Fire/Placebo/issues/16

**Comment by stfwi** [comment]
Ty for the info. Could also be the both mods have independently the same problem ;). So I gonna dig into this at the weekend.

**Comment by stfwi** [comment]
Just double checked my recipe handling, it's in the decor mod completely standard JSON based, only a custom condition applies for opt-out recipe disabling, but this is applied inline in the Forge recipe reloading. So the decor mod itself should not be the source here. 
Also checked Shadows thread again, so gonna close this issue then.
