### ISSUE TITLE
Error occures when starting the Game...

### ISSUE THREAD

**Issue by YourFavFem** [stfwi/engineers-decor#12]
Hi, I really like your Mod but there are some Problems when I tried to play the Game with it.
When I start up the Game it tells me that the Mod hat an Error starting up.
And I'm sorry if your not able to read it its because I'm German.
Can you help me please because I really enjoy your Mod and I would love to play it soon! :)
~AlpherOut
![Problem](https://user-images.githubusercontent.com/48601714/54455167-6abedc80-475b-11e9-9982-72d7f80f81e2.PNG)

**Comment by stfwi** [comment]
Hi, kein Problem, welche Version ist es denn? [en: no problem, which version?]

**Comment by YourFavFem** [comment]
Hi, es ist die Version 1.13.2 :)

**Comment by YourFavFem** [comment]
Also ich habe das ganze erneut Probiert mit der Version wo du es geupdated hast aber das selbe Problem passiert

**Comment by YourFavFem** [comment]
Und nur die Version "**engineersdecor-1.13.2-1.0.0-a2**" hat geklappt.

**Comment by stfwi** [comment]
Ok ich versuche mal das zu reproduzieren.

**Comment by YourFavFem** [comment]
Danke Wirklich nett von dir. :)

**Comment by YourFavFem** [comment]
Aber ich habe da mal eine Frage wie sieht es denn aus mit dem Full Release von den Mod für die 1.13.2? 
Ich würde gerne anfangen damit zur experimentieren usw.

**Comment by stfwi** [comment]
Hi, probier mal `engineersdecor-1.13.2-1.0.2-b2.jar`, ich hatte im Build-System was falsch. Gestestet mit MC1.13.2 / `1.13.2-forge-25.0.84`. 

Mit full release müssen wir warten bis Forge selbst im Release ist. Auch gibt es Immersive Engineering noch nicht für 1.13.2, deshalb habe ich temporäre Rezepte - also Mod-Release wenn Forge und IE da sind. Ich schreib nochmals in Englisch, damit jeder das nachvollziehen kann. Kannst Du Feed back geben ob es OK ist, dann schließen wir das issue. Danke für's Melden, wäre mir nicht aufgefallen weil es in meiner IDE funktioniert hat ;)

***[FTR en:] Startup crash bug fixed in `engineersdecor-1.13.2-1.0.2-b2.jar` (build system setup bug). Mod release version will be available when Forge is released and Immersive Engineering is available for MC1.13.2. Until then the recipes of this mod are temporarily with vanilla ingredients.***

**Comment by YourFavFem** [comment]
I schaue mal obs geht

**Comment by YourFavFem** [comment]
Es funktioniert DANKE :D

**Comment by stfwi** [comment]
Super, dann haken wir das issue ab ;)

***[FTR en]: Fix confirmed. Issue solved.***
