### ISSUE TITLE
[question] datapack processing recipe

### ISSUE THREAD

**Issue by AlleCraft-alterego** [stfwi/engineers-decor#132]
there is datapack processing recipe of small mineral melting furnace ? 
if not, can they be added?

**Comment by stfwi** [comment]
Hi, there is a tag that you can use, which allows the mineral smelter to accept an item as stone-like block. Here's the link to the tag data of the mod, you can extend that using `"replace": false` in the data pack accordingly:
https://github.com/stfwi/engineers-decor/blob/1.16/src/main/resources/data/engineersdecor/tags/items/accepted_mineral_smelter_input.json.
The process itself is "hard-coded", because of the different phases and the cool-down from lava to obsidian.

**Comment by AlleCraft-alterego** [comment]
ok, thanks
