### ISSUE TITLE
[Question] Is it possible to disable items ?

### ISSUE THREAD

**Issue by Redstylt** [stfwi/engineers-decor#133]
Hello,

Sorry to post this question as an issue i couldn't find a discord or an other way to ask...
So is it possible to disable items ? Completely remove an item from the mod (not possible to craft or even see in JEI)

PS: If you have an other way to give a support, let me know

**Comment by stfwi** [comment]
Hi, no worries, opening an issue for questions is absolutely fine. Yes you can disable each item in the mod. In the Server config (`engineersdecor-server.toml`), there is a "opt-out" section. On the one hand some category based features can be disables using `without_<feature name>=true`, on the other hand there is a wildcard based optout using `pattern_excludes="..."`, and `pattern_includes="..."`. This is a comma separated list of registry names and wildcards (like when searching filesystems for "*.txt"), so e.g:

```
pattern_excludes="treated_wood*,small_mineral_smelter,*furnace"
pattern_includes="small_lab_furnace"
```

That would disable everything starting with `treated_wood`, the Mineral Smelter, and all Furnaces except the Small Lab Furnace because that one is explicitly included afterwards. (includes are basically exceptions from excludes ;) ).

All the blocks and items are still registered and still available in the creative menu, so you do not break the game when excluding. They will be hidden in JEI and the recipes will be disabled. You need to `/reload` to make the changes active. In the server log there is also a list of blocks/items opt'ed out, so you can double check. Cheers,-

**Comment by TheSnowyChickens** [comment]
Hello,
according to the config and the disabled items, I have a little issue in 1.16.4 with forge 35.0.15 and ED: 1.1.4-b:

I have disabled some blocks in the config (server.toml) and after restarting MC, the blocks are still ingame with recipes and all the other functions. 
![grafik](https://user-images.githubusercontent.com/29357962/99108284-6b221180-25e7-11eb-996e-bf50b8f4fa39.png)

Am I doing something wrong or is it buggy ?
:D 

Ty
