### ISSUE TITLE
Crash when crafting Small Water Freezer

### ISSUE THREAD

**Issue by thebrightspark** [stfwi/engineers-decor#136]
When crafting the Small Water Freezer, the client crashes with the following error:
https://pastebin.com/hXQ59ZCY

Using version 1.16.3-1.1.3 of this mod and Forge 34.1.42.

**Comment by stfwi** [comment]
Hi, I am on the issue already ;) The thread here was accidentally posted in the Engineer's Tools mod but should be exactly the same issue: https://github.com/stfwi/engineers-tools/issues/14.
Added a mod jar for testing there (because I did not get the error myself), could you take a look if that fixes the problem in your setup? Then I'll push it as release. Cheers!

**Comment by thebrightspark** [comment]
Yes that test jar worked fine 😄

**Comment by stfwi** [comment]
Perfect that, ty for double checking, the fix is pushed for 1.16.3, for 1.16.4 I need to check something before pushing. Closing the issue then. Cheers,-
