### ISSUE TITLE
[suggestion] wood and steel pole autostack when right click with a piece

### ISSUE THREAD

**Issue by Biviho** [stfwi/engineers-decor#139]
hi, i'm making this suggestion in the hope it will be made for 1.12, i don't know if it's already a later version feature.

basically, right clicking on the base of a wood or steel pole with the appropriate piece will autoplace the piece on top of the higher one, making easier to stack them, similar to immersive posts.

an other cool feature would be for the steel post to been able to be right clicked on the base with the double T support and automatically place it on top. Subsequent use of the T support will place them in the direction of the player (the opposite direction on where the player is facing)

**Comment by stfwi** [comment]
Hi biviho, cool ideas; let me check at the weekend how feasible things are in detail. I would first implement it for the mainline and then check in the next step how back-porting can be done. Cheers, -

**Comment by Biviho** [comment]
really happy you like it! your mod have such nice blocks and feature that it was strange this wasn't one!

if backporting will be feasable it will be a really cool feature in my pack: blocks have gravity and need support blocks, and autostack blocks are really valuable on 1.12

**Comment by stfwi** [comment]
Oky, in `engineersdecor-1.16.4-1.1.5` I have tackled the issue. Because there are also horizontal placements, and sometimes placements up-down from scaffolding, I went for a directional placement (player looking direction based) when the pole side is clicked. So when you can't see the head face to click it's possible to click the side of the pole to extend it.

**Comment by stfwi** [comment]
-/approval-timeout/-
