### ISSUE TITLE
Raised catwalks defaultState are waterlogged?

### ISSUE THREAD

**Issue by hvdklauw** [stfwi/engineers-decor#140]
For building gadgets we got an issue report in: https://github.com/Direwolf20-MC/BuildingGadgets/issues/553

I did some digging and it seems the default state for the raised catwalk is waterlogged.

Now I'm not sure if this is a bug or intentional for some reason, but because of placement and block updates we take the default state and then copy all the properties we think are safe to do, waterlogged is not one of them so we don't copy that, but the placed block is waterlogged, so I so seems to come from the default state.

As engineers decor seems to be closed source I have no way to verify this.

We could just always force the waterlogged property to false, but I thought i'd reach out to come to a workable solution.

**Comment by stfwi** [comment]
Hi hvdklauw, I took a quick code peek, you're correct, I have a bug in the constructor of the raised catwalk, in the line here:

https://github.com/stfwi/engineers-decor/blob/efc62d7019f0915f0e7fa4e9c4064f864578668a/src/main/java/wile/engineersdecor/blocks/EdCatwalkTopAlignedBlock.java#L41

... (this should be `setDefaultState(super.getDefaultState().with(VARIANT, 0))`), so that the `WATERLOGGED` property is initialized (the code is located in MC version branches, the `master` branch is only the documentation ;-) ).

Thanks for digging into this also accross mods - not many people do that. I gonna dig dive into the matter at the weekend (also schedule the fix for then), and write a quick note in the Building Gadgets parent thread so that it's confirmed that no action is needed there.

**Comment by hvdklauw** [comment]
Ahh awesome, good to know I can peek at the code, makes future debugging always easier :D

**Comment by stfwi** [comment]
Oky, the fix is in engineersdecor-1.16.4-1.1.4 (up on Curse now). I'll close this issue directly, as the parent issue thread is already closed - if something's coming up we'll reopen it ;-], Cheers,-
