### ISSUE TITLE
Missing Uranium sheet metal slice

### ISSUE THREAD

**Issue by DoomRater** [stfwi/engineers-decor#143]
Spotted in Engineer's Decor 1.1.2 for 1.12.2.  There are sheet metal plates for everything under the sun except uranium sheet metal.  You know, the coolest one because it's green.  Maybe people are too busy feeding their uranium to reactors, but you see, I don't have any.

**Comment by stfwi** [comment]
Yeh, left it out during early development because I noticed that me feet were itching when walking over them :^]

Well, it was basically a design decision - I asked what slices make sense and which would more or less bloat the mod without use. Also Gold slices were already a discussion to be skipped. 

Let me transfer this issue as a +1 to my notes that it's on the screen.
