### ISSUE TITLE
[1.16.4 - 1.1.5] Dark Shingle Roof Blocks Lighting Bugs

### ISSUE THREAD

**Issue by Salamance73** [stfwi/engineers-decor#153]
Hi I'm pretty sure something is wrong with these blocks as they are giving off light, and with the slabs case, very badly so.
[https://imgur.com/g3UstOD](url)

**Comment by stfwi** [comment]
Hi, cheers for reaching out. I was wondering when the first takes notice - it's actually an intended behaviour for the blocks having light level 1. The changes in the vanilla rendering can cause some strange looking shadows in the roof blocks, so this was my workaround for that. I'll double check with the latest Forge version if that problem was addressed there already, otherwise I'll leave the workaround for now.

**Comment by Salamance73** [comment]
I see, I couldn't find much about them so I wasnt sure whether they were intended to do that or not. Thanks for taking a look, love the mod!

**Comment by stfwi** [comment]
Nah ;/ still does not look nice when I disable the LL1-workaround, or try with disabling occlusion etc. Must be that parts of the roof models are stitched surfaces (but with the same plane coords). The renderer puts different external light effects on directly adjacent surfaces - looks awful. So  for the time being the workaround will have to stay (well, it's not The End of the world...). 
Cheers!
