### ISSUE TITLE
Catwalk railing can be stepped over

### ISSUE THREAD

**Issue by Pentasis** [stfwi/engineers-decor#155]
Is it possible to make the catwalk railing hitbox like a fence? Right now I can just step/jump over it. (died once already because of this).

Edit: 1.16.4 obviously, just in case)

**Comment by stfwi** [comment]
Hi, it's technically not a problem, I had that actually implemented in the first experimental version, but removed it because the railings appear to be seen as - well, not fence-like. People did like to have a guard, but found it disturbing that they could not jump over it (including myself). 

Do you use auto jump and accidentally step over the edge? (what we could try to do is to experiment with the collision box height, so that jumping over the railing is possible, but auto jump does not trigger - no idea if that would work though).


As you are a coder, the zero here would have to be increased to a height extension for the collision shape:

https://github.com/stfwi/engineers-decor/blob/61d0225afaa5127579b61e994f89a4441ab20a1f/src/main/java/wile/engineersdecor/blocks/EdRailingBlock.java#L32-L35

**Comment by Pentasis** [comment]
Yeah, I use the StepUp mod to auto"jump" during exploring and mining. But I often forget to turn it off when in my base.
It's not a big issue so I'll just live with it, but just in case I'll ask: would you consider making it an option in the config-file?

**Comment by stfwi** [comment]
(Sorry for the late response busy times ;) ) Let me experiment with the collision shape height at the weekend, maybe this may solve the problem implicitly. Config is principally possible - on the other hand there are already a lot of config options (and more are not exported in the config file but only applied internally to prevent spamming the configs), I'm not sure how dominant/important this setting would be for the majority; just an initial thought, need to evaluate that ;). Cheers!

**Comment by stfwi** [comment]
Ok, experimented a bit, auto jump seems to be exactly one block, and above one block height you cannot jump manually over it (also not 0.5px height increase). It would be technically possible to rebuild the shapes for each railing/catwalk block, but I refrain from doing it because the feature is really a small detail, and I don't like to bloat the mod code too much. So, let's keep it as it is. Cheers!
