### ISSUE TITLE
Allow forcing a fence to render with a metal post

### ISSUE THREAD

**Issue by MatthiasMann** [stfwi/engineers-decor#156]
It would be nice if I could force a steel mesh fence to render a metal post (the one it uses at corners or ends) by right clicking it with the engineer's hammer.

This would make iron bulb lights placed on top look nicer.

Using engineersdecor-1.16.4-1.1.6 with ImmersiveEngineering-1.16.4-4.1.2-129

**Comment by MatthiasMann** [comment]
Or as an alternative have the fence connect to straight thin steel poles (the ones which are used to craft the fence) like it does to steel mesh fence gates.

**Comment by stfwi** [comment]
Hi, the latter is problematic because these are different blocks, and I try to stick to vanilla modelling for the blocks. So the poles would need 4 more model combinations in addition to what they already have that is 16x more resources used for that feature. It would basically bloat up the RAM consumption and game start-up time. I refrain from doing that.

The "hammer sensitive" connection is a good idea and should be feasible, need to double check if the hammer rotation feature passes through if the block cannot be rotated (actually allows the block to detect that the hammer was used on it) .

**Comment by stfwi** [comment]
{preparing repository archiving}
