### ISSUE TITLE
[1.16.5] Block placer does not place blocks, they pop as items.

### ISSUE THREAD

**Issue by ProsperCraft** [stfwi/engineers-decor#179]
https://youtu.be/ktBTaFXooJ4

engineersdecor-1.16.4-1.1.14-b1

**Comment by ProsperCraft** [comment]
Seems similar to https://github.com/stfwi/engineers-decor/issues/176

**Comment by stfwi** [comment]
Hi Goshen, gonna take a glimpse what's doing this. 

There is a setting that may help analysing this in the common config:

```toml
[server.miscellaneous]
  with_debug_logging = true
```

This prints into the log why the placer does spit out an item. The messages start with `Placer spit: ....`.
Would it be possible to forward the request to enable that and attach the logfile here? Currently the reason can vary between "no placement state retrieved from the block" to an exception when placing. 
Cheers man!

**Comment by stfwi** [comment]
Quickly checked, it seems something is blocking the placement. The setup in your video works in my test world and another situation.

![2021-05-29-check-placer](https://user-images.githubusercontent.com/28822525/120061684-9f7a8e00-c05e-11eb-9e87-17724b72f230.png)

I could try to circumvent the problem by forcing a default state placement instead of like-player-clicked-placement, but this may have side effects for other modded blocks, which have to be placed the correct way. Or maybe as a "problem-catch-alternative" placing the default state or so. Let's see, we'll get there ;)

**Comment by stfwi** [comment]
Sorry for the late notification, I could push a `engineersdecor-1.16.4-1.1.14-b2`, where I included circumventing a possible placement prevention (e.g. from external hooks which may affect the default Minecraft fake player instance). 
Would it be possible to check if that helped? Cheers!

**Comment by stfwi** [comment]
Hi guys, is the trouble gone with version b2? Cheers,-

**Comment by stfwi** [comment]
Oky, I presume it's fixed ;)

**Comment by jinkhya** [comment]
Hello, this is happening to me and I'm on 1.1.14. I'm also using them to automate industrial foregoing latex. I dunno how relevant that is.
