### ISSUE TITLE
Request for steel railing

### ISSUE THREAD

**Issue by emanuele246gi** [stfwi/engineers-decor#200]
Hi I'm writing this because I'd really like to see inclined steel railing with classical stairs too, is this possible? I'll wait for a reply! ^^
Also thank you in advance!

**Comment by stfwi** [comment]
Salute, this is unfortunately not possible I'm afraid because the tailings on the metal stairs of the mod are actually part of the stairs block itself, and I tell the stairs to show the railings when clicked with one.
For adding railings to any stairs, the way how Chisels & Bits works would have to be implemented, that is too big for Engineer's Decor. Sorry :/

**Comment by emanuele246gi** [comment]
Oh don't worry! It's not an important thing to me, just an idea ^^
