### ISSUE TITLE
[Feature Request] Port to 1.18.2

### ISSUE THREAD

**Issue by isaaclepes** [stfwi/engineers-decor#206]
1.18.2 compatibility is probably already on your radar.

Thanks for all of your hard work!

**Comment by stfwi** [comment]
Hey Isacc, aye, it's on the list, this time it may take me a while because registration rule has changed in MC since 1.18.2, and I like to handle that in the same manner for all (aka the few) mods I maintain (I can understand Mojang adding a restriction there but it's also goin' on me nerves on the other hand ... ;) )

**Comment by stfwi** [comment]
Alright, 1.18.2 is up ;)
