### ISSUE TITLE
Factory Hopper voids items when broken 

### ISSUE THREAD

**Issue by Sunekaer** [stfwi/engineers-decor#226]
Factory Hoppers void items when broken

Steps to reproduce
    Place factory hopper
    Place item in hopper
    Break hopper

Expected behaviour
Items spill into the world like breaking a regular inventory tile

**Comment by stfwi** [comment]
Hi, the item handler is kaputt, I remember having refactored the deprecated forge handlers, and likely messed that up in turn… I plan to tackle it on this weekend. Cheers, -On 23 Nov 2022, at 15:29, Sunekaer ***@***.***> wrote:﻿
Factory Hoppers void items when broken
Steps to reproduce
Place factory hopper
Place item in hopper
Break hopper
Expected behaviour
Items spill into the world like breaking a regular inventory tile

**Comment by stfwi** [comment]
Oky, v1.18.2-1.1.28 is in process on curse and modrinth. Cheers man,-
