### ISSUE TITLE
[1.18.2] Dependent recipes not working

### ISSUE THREAD

**Issue by Asnro** [stfwi/engineers-decor#231]
I'm building a custom modpack with Immersive Engineering and Engineer's Decor on 1.18.2, and noticed that recipes dependent on IE materials do not work. Old industrial wood requires regular planks, for example. Anything I can do to solve this on my end?

**Comment by stfwi** [comment]
Hi Asnro, 

The tag based conditional recipes I made cannot be used anymore since a change in MC, where the load order "recipes after tags" is not guaranteed anymore. So the marked lines `#forge:treated_wood` (the "official IE notation") can't match anymore, and the alternative fallback recipe is always used.

https://github.com/stfwi/engineers-decor/blob/837b8678f4fb5ebd818d14c5cbb476273be8405b/src/main/resources/data/engineersdecor/recipes/dependent/old_industrial_planks_recipe.json#L5-L10

Pack makers use CraftTweaker (or today JS) to alter the recipes. Fortunately only a small part of my recipes are dependent, so only the recipes in the "dependent" folder would have to be overridden with the custom recipes:

https://github.com/stfwi/engineers-decor/tree/1.18/src/main/resources/data/engineersdecor/recipes

Thinking about it now, we could just replace the tags with the actual exact item registry name. Would narrow down the accepted input item range, but this may not be a problem after all....

If you have a current game setup with IE, could you lookup the item regnames (F3+H, hover) of the IE items? I would update the mod recipes then for a test.

Cheers, wile

**Comment by Asnro** [comment]
Hi, thanks for the response!

I'm not quite sure I understand what you're requesting. Am i supposed to look up each dependent recipe's requirements, then track their registry names down in-game?

**Comment by stfwi** [comment]
Hi, basically I would help to know the IE items for their defined tags (IIRC `immersiveengineering:treated_wood_stick` for `#forge:rods/treated_wood`). That's how pack makers normally do it with the known suspects among the tweak mods. Would that be possible?
