### ISSUE TITLE
Steel beams and pilars break too fast

### ISSUE THREAD

**Issue by MatthiasMann** [stfwi/engineers-decor#32]
I'm using engineersdecor-1.12.2-1.0.8 and the diamond drill from IC2 and the steel T supports break as fast as sand.

I think they should have the hardness of either the IE steel block or obsidian.

**Comment by stfwi** [comment]
Hi, I'll double check this. Because it's a purely decorative block I tend to make the hardness a bit lower than normally, reference is how much time you need with an iron pick without getting annoyed if you misplaced some poles and have to relocate them. But the value might be too low now. It will not be as hard as the steel block, more something between stone and steel.

**Comment by stfwi** [comment]
I raised the hardness values for these block, so should be OK now.
