### ISSUE TITLE
[Suggestion] Hollow scaffolding

### ISSUE THREAD

**Issue by LeoBeliik** [stfwi/engineers-decor#46]
steel and aluminum scaffolding with the bottom and front side open, so it can be used with this (https://imgur.com/JAunsme) setup.

so basically it'd looks like this https://imgur.com/xdBDKOd
alternatively https://imgur.com/2HBlfiD

Cheerio  😄

**Comment by stfwi** [comment]
Hi - cheers for the suggestion. I would recommend to place this request in ImmersiveEngineering itself, because these blocks have to be conveyors to make your shown setup working. 
Conveyors are a basic part of the core IE, addons should tackle them. 
BluSunrize and Malte are very open for ideas - give it a try in the [IE](https://github.com/BluSunrize/ImmersiveEngineering) repository, I am sure they will answer. Cheers -

**Comment by stfwi** [comment]
Leo, did you get a response from the IE repo (can we close this issue here)? cheers -

**Comment by LeoBeliik** [comment]
Oh sorry, yes you can close :)
