### ISSUE TITLE
[Mod Support Request] Dynamic Trees compatibility Factory Block Placer

### ISSUE THREAD

**Issue by Lordician** [stfwi/engineers-decor#57]
While the tree cutter works great now, i noticed another aspect that could work better with the mod.
**Factory Block Placer**
This block has the ability to plant normal saplings, however, Dynamic Trees uses different seeds (like the oak acorn) for Dynamic Trees. A configuration option exists for the Dynamic Trees mod to use saplings instead, but the seeds look better and some have some small behavioral differences as items.
Could we perhaps see support to plant these using the factory block placer as well?

This issue was found using the following setup:
1.12.2-forge1.12.2-14.23.5.2838
ImmersiveEngineering-0.12-92
engineersdecor-1.12.2-1.0.15-b2
DynamicTrees-1.12.2-0.9.5

**Comment by stfwi** [comment]
Hmm I must have a bug in the handling of (so called) "plantable" items, this stuff is pretty well defined in MC/Forge.

**Comment by stfwi** [comment]
No, actually Dynamic Trees does not implement that IPlantable standard. Oh man that's a bummer.

**Comment by Lordician** [comment]
I figured something like that would be the case.
Do i need to put an issue over at Dynamic Trees to ask him to make them use that Interface?
Also, will it still be possible to do something about this?

**Comment by stfwi** [comment]
From my point of view it would be the right thing if the DT dev would be triggered here. I am reluctant adding a hard dependency in the mod (that could break my mod) for a quite small compat aspect compared to the normal feature set. There's also the thing that there is a standard for plantable items and blocks, and sticking to that is the best way for having compat.

So, let's close this issue here and I'll put it on my analog list. When something crosses the roads that can help without compat problems seen ahead, it'll be implemented.
