### ISSUE TITLE
[Suggestion] Giant Mushrooms & Tree Cutter (Or Something Similar)

### ISSUE THREAD

**Issue by DracoShadow** [stfwi/engineers-decor#66]
If it's entirely possible, could it be added that the tree cutter (or something like it) could chop down giant mushrooms? I'd think it'd be a useful addition personally if say you don't have a method of growing mushrooms like in the IE Cloche.

**Comment by stfwi** [comment]
Hi, let me think about this in the next days. The AE Menril is already treated as a special block detected as the same "wood log type", so extending this should be possible. I am wondering if it would make sense to add a kind of config option (e.g. semicolon separated string) to freely configure what blocks to make choppable. Need to double check if that can be done with moderate performance.

**Comment by stfwi** [comment]
Ok, I have taken a look into this, the tree contour detection that I implemented would have to be mutated to a primitive vein mining (because Shrooms have no leaves and go almost down to the ground again with the caps). So I would like to close this one and make a note in my analog FR list. So if/when I rewrite the tree chopping for some reason, then the FR will be included.
