### ISSUE TITLE
new textures arent 16x16

### ISSUE THREAD

**Issue by majijn** [stfwi/engineers-decor#7]
![2019-03-04_00 49 15](https://user-images.githubusercontent.com/18368034/53704204-d4192400-3e1a-11e9-8f46-dbd655be768b.png)
it clashes with other blocks like this

**Comment by stfwi** [comment]
Hi, thanks for beta testing, man! Yeah it was the first shot of the model. I am also not happy with it, not only the texture, but also the height. I will rework the model for the next beta, so that it should fit well when standing next to a original IE Engineer's workbench. So the top plate dimensions, and likely a steelish drawer and legs.

**Comment by stfwi** [comment]
![2019-03-04-model-crafting-table](https://user-images.githubusercontent.com/28822525/53732415-26d7f780-3e7e-11e9-81fc-79b0112cf883.png)

**Comment by stfwi** [comment]
I think let's go with something like this.

**Comment by majijn** [comment]
that one is SO beautiful! nice work!

**Comment by stfwi** [comment]
Cheers. So I close this one. There is still something bugging me with the tooltip, which is for whatever reason below the JEI, but that's another topic ;).
