### ISSUE TITLE
Incompatibility with RealBench mod

### ISSUE THREAD

**Issue by Voxel-Friend** [stfwi/engineers-decor#8]
When the mod "realbench" is included, your crafting table will delete items left in the table. I would like to either see compatibility with the mod, or similar functionality added to your mod, which I would prefer, as it would be even more reason to use it over vanilla.

**Comment by stfwi** [comment]
Currently the crafting table should not keep the inventory at all.

Hi, I am still working on that bench. It will have 8 additional storage slots, keep its inventory, and also keep it when you break it and place it somewhere else. I have an issue with the tile entity data saving at the moment, that's why I did not push it yet ;). So - yes it will be better ;)

**Comment by stfwi** [comment]
Ok, think I solved that entity issue. Check v1.0.1-b4. According to realbench: I don't know what realbench does to crafting inventories, it will be a hard thing to be compatible with a mod that changes slots in other mods containers.

**Comment by stfwi** [comment]
In release now, so I close this.
