### ISSUE TITLE
[1.14.4] factory placer sometimes ejects seeds/potatoes/carrots

### ISSUE THREAD

**Issue by jcardii** [stfwi/engineers-decor#83]
I am trying to reliably duplicate this issue. I have one save world that exhibits problem below.
v1.14.4, later Forge (.117), other mods.
Place dirt. Add water close enough to hydrate dirt. Install Factory Placer facing up into dirt. Load some (half-stack) seeds/carrots/potatoes into placer. Hoe the dirt into farmland. Expected placer to plant seeds, instead placer will begin to eject items one-by-one until empty.

If I place dirt, then water, then Placer below it, then hoe it, then add seeds, seems to work as expected.

**Comment by jcardii** [comment]
Might be duplicate of #64

**Comment by jcardii** [comment]
Missed a detail - when hoeing, dirt was still dirt, not grass.

**Comment by stfwi** [comment]
Hi, wow, I tried to reproduce that without any success until now, this weekend I can take a closer look. Cheers -

**Comment by stfwi** [comment]
Ok, I found a location in the code that could have effect on that problem (if planting the block with the  "standard Minecraft fake player" fails). It could be that another mod uses that global entity and altered it somehow temporarily or adds hooks etc, so that this happens. In that case I try to place the plant now manually.
The only other situation where the Placer spits out plants is if the soil underneath says it cannot sustain plant, that is unlikely.

**Comment by stfwi** [comment]
Ok the suspicious code is hopefully circumvented now. I could not reproduce the problem but pushed the the new version with the probable-fix on curse. Could you double check if you still get this effect?

**Comment by stfwi** [comment]
Taking this as a "yes" ;)
