### ISSUE TITLE
NEW Dupe bug in Treated wood Crafting Table

### ISSUE THREAD

**Issue by Nachtflame** [stfwi/engineers-decor#88]
Hello again!
This time an interaction between your _Treated Wood Crafting Table_, and the mod **Inventory Sorter** by _cpw_
Steps to reproduce:
- Place any item(s) in crafting grid, retaining at least 1 more in player inventory or SideStorage for table
- Use hotkey (def: Middle-Click) to attempt to sort either inventory of Table (mouse hovering them)
- Watch in horrified amazement as the stack in the crafting grid, increases by _TOTAL COUNT_ of that item present in the (storage slots + Players inventory)

MC 1.15.2
ED - 1.0.19-b3
Inventory Sorter - 17.0.0

Was going to report it to other author as well, but their project description seems to have a clue as the issue and hopefully gives you an idea of how to fix on your end - 

> /inventorysorter [arg]
>
>It interacts with the last container you middle click sorted (or attempted to), to allow you to manipulate the container blacklist. These are containers that don't respect middleclick sorting for one reason or another (typically where a special slot containing a special item is not properly marked read only, allowing for it to be duped instead).

And yes, I followed his instructions to blacklist the table, to no effect. (Command ran properly, stating success in blacklisting, but table still dupes)

**Comment by stfwi** [comment]
Hmm, I am pretty sure cpw knows what he is doing - this must be an issue with the crafting table. I may get time this weekend to take a look into this. Thanks for the hint already!

**Comment by stfwi** [comment]
Ok, quick update about the first impression, I made in 1.14.4 a check (as my code is almost identical), and cannot reproduce it there. So cannot be much to find that problem in 1.15.2.
(edit -> And, boooom, happens when the items are identical with tag - and that also in 1.14, oh man).

--> It's related to the crafting grid inventory, which is not the player inventory and is handled specially in the inventorysorter. I simply made a special slot type and blacklisted it via IMC, so the issue should be solved in the next version. The inventorysorter config is somehow not loaded, probably gonna make an issue or PR for cpw.

**Comment by stfwi** [comment]
Ok, also took a glance into the inventorysorter code, could be that a definition which kind of config (server, client, both) may have to be changed there (I am not sure there), so cpw is informed.
(issue is https://github.com/cpw/inventorysorter/issues/88).

**Comment by Nachtflame** [comment]
Definitely able to do it myself on 1.14.4. At least on dedicated server,
hadn't tested on SP (not at my computer to check at the moment)
forge-28.2.1
Engineers decor 1.0.9-b3
Inventory Sorter 16.2.0

**Comment by stfwi** [comment]
Server config should be fine on dedicated servers. I noticed a sorter crash while testing SP without dedicated server. Let’s see what cpw says.

**Comment by stfwi** [comment]
Alright, the version `1.0.19-b4` contains the inventorysorter blacklisting for 1.15.2. 
I commented that out yet for 1.14.4 until it's clarified with cpw if can can fire a crash in the inventorysorter (had to decide here - crash is worse than duping ;/ ).
Can you double check if the issue is resolved for you on 1.15.2?

**Comment by Nachtflame** [comment]
Fixed the issue for 1.14.4 at least, my experience on 1.15.2 was with a pack I was testing, will let the author know.
